import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useQuery } from "@apollo/client"
import GET_ALL_TOPICS_QUERY from "@/apollo/queries/getAllTopcisQuery"



export default function Home() {
const { loading, error, data } = useQuery(GET_ALL_TOPICS_QUERY)

const renderData = () => {
	if (loading) return <p>Loading...</p>
	if (error) return <p>Error :(</p>
	return data.getAllTopics.map((topic: any) => (
		<div key={topic.id}>
			<p>{topic.title}</p>
		</div>
	))
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
		{renderData()}
      </main>
    </>
  )
}
